apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: python-tvrtqcmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-tvrtqcmn 
  name: python-tvrtqcmn
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-tvrtqcmn
    weight: 100 
